### ISSUE TITLE
script error...

### ISSUE THREAD

**Issue by badman74** [Dimencia/DU-Orbital-Hud#8] opened 2020-09-20 14:09 UTC
throwing a script error when pitchSpeedFactor is set at 0.8, changing it to .8 seems to work though (was default)

**Comment by badman74** [comment] 2020-09-20 17:14
it appears this may only occur if your pitch is exactly 0, it seems to come and go....

**Comment by Dimencia** [comment] 2020-09-20 18:27
What control scheme are you using?  Regular mouse?  Will try to reproduce

**Comment by badman74** [comment] 2020-09-20 19:18
Mouse, seems like it happens more if you are setting on a level surface

**Comment by LiPeK** [comment] 2020-09-21 19:48
There is a script error in functions GetAutopilotBrakeDistanceAndTime, GetAutopilotTBBrakeDistanceAndTime
The unit.getData() JSON string sometimes doesn't contain the maxBrake parameter.

**Comment by Dimencia** [comment] 2020-09-21 20:02
Well that's helpful, I thought getData was coming back nil.   But yeah, basically DU is buggy AF, and sometimes it just doesn't do what it's supposed to.  All I can recommend is a restart of the game

I've been looking into alternatives to getData, and basically I can't reliably and accurately calculate the brake distance otherwise (unless you type in values for which skills you have).  I wouldn't send someone on an autopilot journey if the brake distances weren't accurate, so, just gotta restart if the game stops giving us the data

**Comment by Dimencia** [comment] 2020-09-21 23:18
Alright, just pushed an update that should basically fix this.  Experienced it myself a few times which helped - I found out this only happens for like, a tick at a time.  So, it just stores the maxBrake each time it can read it.  If it can't read it, it just uses the previous value

Closing issue, I believe this was also the cause of the original script error badman was having

**Closed by Dimencia** 2020-09-21 23:18 UTC
