### ISSUE TITLE
Loss of Throttle Control During Space Flight

### ISSUE THREAD

**Issue by Trotsky21** [Dimencia/DU-Orbital-Hud#182] opened 2020-12-08 10:14 UTC
Leaving ship (hitting f) during space flight (flight between two planets, about 4 or more SU from nearest planet), and then re-entering ship (hitting f again while pointed at ship) has resulted in the loss of throttle control each time it has been done. It also generates several screen messages generated by the script which are unrelated to the actual situation of the ship.

**Comment by ristlin** [comment] 2020-12-15 03:11
Can you double check that your command chair is connected to the right data bank?

**Comment by Trotsky21** [comment] 2020-12-18 14:31
I don't have a data bank on that particular ship.

**Comment by Archaegeo** [comment] 2021-01-11 21:36
Closing this as I cannot reproduce it.  If it recurs, provide more details.

**Closed by Archaegeo** 2021-01-11 21:36 UTC
